# Generated by Django 5.0.2 on 2025-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_item_id_item_id_remove_transaction_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='Vendor_ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Item_ID'),
            preserve_default=False,
        ),
    ]
